SOLVER:
  gpu: 0,
  logdir: logs/ocnn_5_2_dropout_00_00
  run: train
  max_iter: 10000
  test_iter: 300
  test_every_iter: 500
  step_size: (5000,)
  learning_rate: 0.1

DATA:
  train:
    dtype: octree_with_vector
    distort: False
    depth: 5
    location: dataset/train_5_2_1.tfrecords
    shuffle: 100
    batch_size: 32
    x_alias: data
  test: 
    dtype: octree_with_vector
    distort: False
    depth: 5
    location: dataset/test_5_2_1.tfrecords
    shuffle: 0
    batch_size: 1
    x_alias: data

MODEL:
  name: ocnn
  channel: 3
  nout: 36
  depth: 5
  dropout: (0.5, 0.5)

LOSS:
  weight_decay: 1e-6
